apiVersion: v1
kind: ServiceAccount
metadata:
  name: hokiehelp-admin
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hokiehelp-admin-logs
  namespace: test
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hokiehelp-admin-logs
  namespace: test
subjects:
  - kind: ServiceAccount
    name: hokiehelp-admin
    namespace: test
roleRef:
  kind: Role
  name: hokiehelp-admin-logs
  apiGroup: rbac.authorization.k8s.io
