apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: admin-data
  namespace: test
  labels:
    app: hokiehelp-admin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
