apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: test
  labels:
    app: minio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 10Gi
