apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-data
  namespace: test
  labels:
    app: qdrant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 5Gi
